name: Unit Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Set Up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Launching Database on Docker
        run: |
          docker run --detach \--env MYSQL_ROOT_PASSWORD=user \--env MYSQL_USER=user \--env MYSQL_PASSWORD=user \--env MYSQL_DATABASE=mydatabase \--name mysql \--publish 3306:3306 mysql:8-oracle

      - name: Test
        run: mvn test -DskipTests=false

      - name: Have github action to create maven build
        run: |
          mvn -B package --file pom.xml
          mkdir staging && cp target/*.jar staging

      - name: Persist workflow data as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: staging

      - name: Validate Packer Script
        run: packer validate ami .
